name: molecule

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sat'

jobs:
  test:
    name: ${{ matrix.image }} python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - centos:8
          - centos:7
          - fedora:39
          - fedora:38
          - ubuntu:22.04
          - ubuntu:20.04
          - ubuntu:18.04
          - debian:12
          - debian:11
          - oraclelinux:8
          - oraclelinux:7
          - amazonlinux:2
          - archlinux:latest
        python_version:
          - 3.12.2
          - 3.11.9
          - 3.10.14
          - 3.9.19
          - 3.8.19

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Molecule
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Test Ansible role
        run: molecule test
        env:
          image: ansible-${{ matrix.image }}
          python_version: ${{ matrix.python_version }}
